# Generated by Django 3.2.5 on 2021-08-08 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ManyToManyField(related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='max_bid',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='active',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
