# Generated by Django 3.2.5 on 2021-08-08 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210808_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ManyToManyField(blank=True, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
