# Generated by Django 3.2.5 on 2021-08-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='max_bid',
            field=models.BooleanField(blank=True, db_index=True),
        ),
    ]
