# Generated by Django 3.2.5 on 2021-08-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210811_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
