# Generated by Django 3.2.5 on 2021-08-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.IntegerField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
